server:
  port: 9000

# API Gateway Configuration for routings and load balancing

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            
      routes:
      - id: bankloan-service
        uri: lb://bankloan-service
        predicates:
        - Path=/api/v1/bankloan/**

      - id: loan-service
        uri: lb://loan-service
        predicates:
        - Path=/api/v1/loan/**
        
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/v1/customerservice/**

      - id: creditcard-service
        uri: lb://creditcard-service
        predicates:
          - Path=/api/v1/creditcard/**
          
      - id: bank-service
        uri: lb://bank-service
        predicates:
        - Path=/api/v1/bankservice/**
        
       
