server:
  port: 9000

# API Gateway Configuration for routings and load balancing

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/v1/customer/**
       
       
      - id: mobile-service
        uri: lb://mobile-service
        predicates:
        - Path=/api/v1/mobile/**
          
